"""add_product_id_to_cart_items

Revision ID: 169d9e6913da
Revises: e224f1389a0b
Create Date: 2026-02-20 12:53:40.883075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169d9e6913da'
down_revision: Union[str, Sequence[str], None] = 'e224f1389a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('product_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'product_id')
    # ### end Alembic commands ###
