"""Add customization field to cart item

Revision ID: 3b753fc2b989
Revises: b9aedff97321
Create Date: 2026-02-16 17:59:45.065183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b753fc2b989'
down_revision: Union[str, Sequence[str], None] = 'b9aedff97321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('is_customized', sa.Integer(), nullable=True))
    op.add_column('cart_items', sa.Column('design_logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'design_logo')
    op.drop_column('cart_items', 'is_customized')
    # ### end Alembic commands ###
