"""add logo and placement to customized_product

Revision ID: b9aedff97321
Revises: 9810e88c10a1
Create Date: 2026-02-16 15:37:23.751292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9aedff97321'
down_revision: Union[str, Sequence[str], None] = '9810e88c10a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customized_products', sa.Column('design_logo', sa.String(), nullable=True))
    op.add_column('customized_products', sa.Column('placement_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customized_products', 'placement_data')
    op.drop_column('customized_products', 'design_logo')
    # ### end Alembic commands ###
